# Generated by Django 5.1.1 on 2024-09-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_question_category_alter_question_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date_created',
        ),
    ]
