# Generated by Django 5.1.1 on 2024-09-09 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_remove_question_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
