# Generated by Django 5.1.1 on 2024-09-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_alter_question_subject_question_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
    ]
